title: OpenStreetMap Foundation - DMCA Notice Procedure
description: "How to send a DMCA notice to the OpenStreetMap Foundation."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dmca.openstreetmap.org" # the base hostname & protocol for your site, e.g. http://example.com

markdown: kramdown

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gzip

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
